# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 803bf44ee11ec313e1049a70cb57f24936f8580be45f04a779de69c3ca92caa764b6ea8f8be2a299756941087262e4b816bfc523e9105ff3dbb84b70d3509e09

test:
  secret_key_base: 16174ff11118f5710cc9c8474917c365558e8ee228151c802c1eb4c860fc3bc753f304c9d8feabbe3569cf8fd0d4b790fbcacb3de3116caf02da84d99d8ee3ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
